package GUI;

import DTO.NhanVienDTO;
import javax.swing.*;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;

import java.awt.*;
import javax.swing.border.EmptyBorder;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author QUAN
 */
public class Main extends javax.swing.JFrame {
    // Panel
    private SanPham sanphamPanel;
    private NhaCungCap nhacungcapPanel;
    private KhachHang khachHangPanel;
    private NhanVien nhanVienPanel;
    private ThuocTinh thuocTinhPanel;
    private PhieuNhap phieuNhapPanel;
    private HoaDon hoaDonPanel;
    private ThongKe thongKePanel;
    private NhomQuyen nhomQuyenPanel;
    private final NhanVienDTO nhanVien; // lưu lại nhân viên đăng nhập

    /** Creates new form Main
     * @param nhanVien */
    public Main(NhanVienDTO nhanVien) {
        this.nhanVien = nhanVien;
        // Setup Frame Attributes
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Hệ thống quản lý cửa hàng nước hoa");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        // Init Frame's Components 
        setUT();
        initComponents();
        addIconTaskbar();
        
        
        // ✅ Gán tên và chức vụ
    lblTenNhanVien.setText(nhanVien.getName());
    lblChucVu.setText(nhanVien.getRoleGroupName());
    
    phanQuyenTheoVaiTro();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuTaskbar = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        lblTenNhanVien = new javax.swing.JLabel();
        bar = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        taskBar = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JToggleButton("<html>&nbsp;&nbsp;&nbsp;Trang chủ</html>");
        btnSanPham = new javax.swing.JToggleButton();
        btnThuocTinh = new javax.swing.JToggleButton();
        btnPhieuNhap = new javax.swing.JToggleButton();
        btnHoaDon = new javax.swing.JToggleButton();
        btnKhachHang = new javax.swing.JToggleButton();
        btnNhaCungCap = new javax.swing.JToggleButton();
        btnNhanVien = new javax.swing.JToggleButton();
        btnThongKe = new javax.swing.JToggleButton();
        btnNhomQuyen = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        mainContent = new javax.swing.JPanel();
        mainContent2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        menuTaskbar.setBackground(new java.awt.Color(255, 255, 255));
        menuTaskbar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuTaskbar.setPreferredSize(new java.awt.Dimension(200, 800));
        menuTaskbar.setLayout(new java.awt.BorderLayout());

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setPreferredSize(new java.awt.Dimension(136, 70));

        lblTenNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblTenNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenNhanVien.setText("Lê Nguyễn Hoàng Phát");

        bar.setBackground(new java.awt.Color(0, 0, 0));
        bar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        bar.setPreferredSize(new java.awt.Dimension(1, 1));

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(153, 153, 153));
        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChucVu.setText("Quản lý kho");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(lblChucVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTenNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuTaskbar.add(info, java.awt.BorderLayout.NORTH);

        taskBar.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(btnTrangChu);
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnSanPham);
        btnSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSanPham.setText("Sản phẩm");
        btnSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnThuocTinh);
        btnThuocTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThuocTinh.setText("Thuộc tính");
        btnThuocTinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuocTinhActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnPhieuNhap);
        btnPhieuNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPhieuNhap.setText("Phiếu nhập");
        btnPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuNhapActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnHoaDon);
        btnHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHoaDon.setText("Hóa Đơn");
        btnHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnKhachHang);
        btnKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnNhaCungCap);
        btnNhaCungCap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNhaCungCap.setText("Nhà cung cấp");
        btnNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnNhanVien);
        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnThongKe);
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnNhomQuyen);
        btnNhomQuyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNhomQuyen.setText("Nhóm quyền");
        btnNhomQuyen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhomQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhomQuyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout taskBarLayout = new javax.swing.GroupLayout(taskBar);
        taskBar.setLayout(taskBarLayout);
        taskBarLayout.setHorizontalGroup(
            taskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThuocTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhaCungCap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(btnNhomQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        taskBarLayout.setVerticalGroup(
            taskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTrangChu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSanPham)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThuocTinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPhieuNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhachHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhaCungCap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        menuTaskbar.add(taskBar, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(111, 70));

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnDangXuat)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menuTaskbar.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(menuTaskbar, java.awt.BorderLayout.WEST);

        mainContent.setBackground(new java.awt.Color(235, 235, 235));
        mainContent.setPreferredSize(new java.awt.Dimension(1200, 800));
        mainContent.setLayout(new java.awt.BorderLayout());

        mainContent2.setBackground(new java.awt.Color(235, 235, 235));

        javax.swing.GroupLayout mainContent2Layout = new javax.swing.GroupLayout(mainContent2);
        mainContent2.setLayout(mainContent2Layout);
        mainContent2Layout.setHorizontalGroup(
            mainContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        mainContent2Layout.setVerticalGroup(
            mainContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        mainContent.add(mainContent2, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
        this.sanphamPanel = new SanPham();
        addTaskBar(mainContent2, sanphamPanel);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuocTinhActionPerformed
        // TODO add your handling code here:
        this.thuocTinhPanel = new ThuocTinh();
        addTaskBar(mainContent2, thuocTinhPanel);
    }//GEN-LAST:event_btnThuocTinhActionPerformed

    private void btnPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuNhapActionPerformed
        // TODO add your handling code here:
        this.phieuNhapPanel = new PhieuNhap();
        addTaskBar(mainContent2, phieuNhapPanel);
    }//GEN-LAST:event_btnPhieuNhapActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        // TODO add your handling code here:
        this.hoaDonPanel = new HoaDon();
        addTaskBar(mainContent2, hoaDonPanel);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        this.khachHangPanel = new KhachHang();
        addTaskBar(mainContent2, khachHangPanel);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
        // TODO add your handling code here:
        this.nhacungcapPanel = new NhaCungCap();
        addTaskBar(mainContent2, nhacungcapPanel);
    }//GEN-LAST:event_btnNhaCungCapActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        this.nhanVienPanel = new NhanVien();
        addTaskBar(mainContent2, nhanVienPanel);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        this.thongKePanel = new ThongKe();
        addTaskBar(mainContent2, thongKePanel);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnNhomQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhomQuyenActionPerformed
        // TODO add your handling code here:
        this.nhomQuyenPanel = new NhomQuyen();
        addTaskBar(mainContent2, nhomQuyenPanel);
    }//GEN-LAST:event_btnNhomQuyenActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose(); // đóng form hiện tại
        new Login().setVisible(true); // mở lại form login
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void addIconTaskbar() {

        btnDangXuat.setText("<html>&nbsp;&nbsp;&nbsp;Đăng xuất</html>");
        btnKhachHang.setText("<html>&nbsp;&nbsp;&nbsp;Khách hàng</html>");
        btnNhaCungCap.setText("<html>&nbsp;&nbsp;&nbsp;Nhà cung cấp</html>");
        btnNhanVien.setText("<html>&nbsp;&nbsp;&nbsp;Nhân viên</html>");
        btnPhieuNhap.setText("<html>&nbsp;&nbsp;&nbsp;Phiếu Nhập</html>");
        btnHoaDon.setText("<html>&nbsp;&nbsp;&nbsp;Hóa Đơn</html>");
        btnSanPham.setText("<html>&nbsp;&nbsp;&nbsp;Sản phẩm</html>");
        btnThongKe.setText("<html>&nbsp;&nbsp;&nbsp;Thống kê</html>");
        btnThuocTinh.setText("<html>&nbsp;&nbsp;&nbsp;Thuộc tính</html>");
        btnTrangChu.setText("<html>&nbsp;&nbsp;&nbsp;Trang chủ</html>");
        btnNhomQuyen.setText("<html>&nbsp;&nbsp;&nbsp;Nhóm Quyền</html>");

        // Đặt icon và căn chỉnh biểu tượng sang trái cho mỗi button
        btnTrangChu.setIcon(new FlatSVGIcon("res/icon/home.svg"));
        btnTrangChu.setHorizontalAlignment(SwingConstants.LEFT);

        btnSanPham.setIcon(new FlatSVGIcon("res/icon/product.svg"));
        btnSanPham.setHorizontalAlignment(SwingConstants.LEFT);

        btnThuocTinh.setIcon(new FlatSVGIcon("res/icon/brand.svg"));
        btnThuocTinh.setHorizontalAlignment(SwingConstants.LEFT);

        btnPhieuNhap.setIcon(new FlatSVGIcon("res/icon/import.svg"));
        btnPhieuNhap.setHorizontalAlignment(SwingConstants.LEFT);

        btnHoaDon.setIcon(new FlatSVGIcon("res/icon/export.svg"));
        btnHoaDon.setHorizontalAlignment(SwingConstants.LEFT);

        btnKhachHang.setIcon(new FlatSVGIcon("res/icon/customer.svg"));
        btnKhachHang.setHorizontalAlignment(SwingConstants.LEFT);

        btnNhaCungCap.setIcon(new FlatSVGIcon("res/icon/supplier.svg"));
        btnNhaCungCap.setHorizontalAlignment(SwingConstants.LEFT);

        btnNhanVien.setIcon(new FlatSVGIcon("res/icon/staff.svg"));
        btnNhanVien.setHorizontalAlignment(SwingConstants.LEFT);

        btnThongKe.setIcon(new FlatSVGIcon("res/icon/statistical.svg"));
        btnThongKe.setHorizontalAlignment(SwingConstants.LEFT);
        
        btnNhomQuyen.setIcon(new FlatSVGIcon("res/icon/nhomquyen.svg"));
        btnNhomQuyen.setHorizontalAlignment(SwingConstants.LEFT);

        btnDangXuat.setIcon(new FlatSVGIcon("res/icon/log_out.svg"));
        btnDangXuat.setHorizontalAlignment(SwingConstants.LEFT);
    }
    
    private void setUT() {
        FlatRobotoFont.install();
        // set font chữ
        FlatLaf.setPreferredFontFamily(FlatRobotoFont.FAMILY); // set size cho font 
        FlatLaf.setPreferredLightFontFamily(FlatRobotoFont.FAMILY_LIGHT);
        FlatLaf.setPreferredSemiboldFontFamily(FlatRobotoFont.FAMILY_SEMIBOLD);
        FlatIntelliJLaf.registerCustomDefaultsSource("style");
        FlatIntelliJLaf.setup();

        UIManager.put("Table.showVerticalLines", false); // ẩn đường kể dọc
        UIManager.put("Table.showHorizontalLines", true); // hiện đường kẻ ngang
        UIManager.put("TextComponent.arc", 30);

        UIManager.put("Button.arc", 10); // Thiết lập đường cong là 10 pixel

        UIManager.put("ScrollBar.thumbArc", 999);
        UIManager.put("ScrollBar.thumbInsets", new Insets(2, 2, 2, 2));
        UIManager.put("Button.iconTextGap", 10);

        UIManager.put("PasswordField.showRevealButton", true);

        UIManager.put("Table.selectionBackground", new Color(240, 247, 250));
        UIManager.put("Table.selectionForeground", new Color(0, 0, 0));
        UIManager.put("Table.scrollPaneBorder", new EmptyBorder(0, 0, 0, 0));
        UIManager.put("Table.rowHeight", 40);
        UIManager.put("TabbedPane.selectedBackground", Color.white);
        UIManager.put("TableHeader.height", 40);
        UIManager.put("TableHeader.font", UIManager.getFont("h4.font"));
        UIManager.put("TableHeader.background", new Color(242, 242, 242));
        UIManager.put("TableHeader.separatorColor", new Color(242, 242, 242));
        UIManager.put("TableHeader.bottomSeparatorColor", new Color(242, 242, 242));
        btnTrangChuActionPerformed(null);
    }

    private void addTaskBar(Container mainContent, JPanel panel) {
        mainContent.setLayout(new BorderLayout());
        panel.setSize(mainContent.getSize());
        mainContent.removeAll();
        mainContent.add(panel, BorderLayout.CENTER);
        mainContent.setVisible(true);
        mainContent.revalidate();
        mainContent.repaint();
    }
    private void phanQuyenTheoVaiTro() {
    int role = nhanVien.getRoleGroupId();

    if (role == 1) return; // Admin: full quyền
    if (role == 2) {
        btnNhanVien.setVisible(false);
        btnNhomQuyen.setVisible(false);
        btnThongKe.setVisible(false);
        btnPhieuNhap.setVisible(false);
        btnThuocTinh.setVisible(false);
        btnNhaCungCap.setVisible(false);
        btnKhachHang.setVisible(false);
    }
    if (role == 3) {
        btnNhanVien.setVisible(false);
        btnNhomQuyen.setVisible(false);
    }

    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bar;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JToggleButton btnHoaDon;
    private javax.swing.JToggleButton btnKhachHang;
    private javax.swing.JToggleButton btnNhaCungCap;
    private javax.swing.JToggleButton btnNhanVien;
    private javax.swing.JToggleButton btnNhomQuyen;
    private javax.swing.JToggleButton btnPhieuNhap;
    private javax.swing.JToggleButton btnSanPham;
    private javax.swing.JToggleButton btnThongKe;
    private javax.swing.JToggleButton btnThuocTinh;
    private javax.swing.JToggleButton btnTrangChu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel mainContent2;
    private javax.swing.JPanel menuTaskbar;
    private javax.swing.JPanel taskBar;
    // End of variables declaration//GEN-END:variables

}
