/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package GUI;

import GUI.ThongKeHeThong.ThongKeDoanhThu;
import GUI.ThongKeHeThong.ThongKeDoanhThuTungNam;
import GUI.ThongKeHeThong.ThongKeDoanhThuTungThang;
import GUI.ThongKeHeThong.ThongKeKhachHang;
import GUI.ThongKeHeThong.ThongKeNhaCungCap;
import GUI.ThongKeHeThong.ThongKeSanPhamBanChay;
import GUI.ThongKeHeThong.ThongKeTonKho;
import GUI.ThongKeHeThong.ThongKeTongQuan;
import GUI.ThongKeHeThong.ThongKeTrongThang;
import GUI.ThongKeHeThong.ThongKeTuNgayDenNgay;
/**
 *
 * @author hoang
 */
public class ThongKe extends javax.swing.JPanel {
    // Tabpane's Tabs
    private ThongKeDoanhThu doanhThuTab;
    private ThongKeDoanhThuTungNam doanhThuTungNamTab;
    private ThongKeDoanhThuTungThang doanhThuTungThangTab;
    private ThongKeKhachHang khachHangTab;
    private ThongKeNhaCungCap nhaCungCapTab;
    private ThongKeSanPhamBanChay sanPhamBanChayTab;
    private ThongKeTonKho tonKhoTab;
    private ThongKeTongQuan tongQuanTab;
    private ThongKeTrongThang trongThangTab;
    private ThongKeTuNgayDenNgay khoangThoiGianTab;
    
    /** Creates new form ThongKe */
    public ThongKe() {
        initComponents();
        initTabs();
        addTabs();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaneThongKe = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(tabPaneThongKe, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initTabs() {
        doanhThuTab = new ThongKeDoanhThu();
        doanhThuTungNamTab = new ThongKeDoanhThuTungNam();
        doanhThuTungThangTab = new ThongKeDoanhThuTungThang();
        khachHangTab = new ThongKeKhachHang();
        nhaCungCapTab = new ThongKeNhaCungCap();
        sanPhamBanChayTab = new ThongKeSanPhamBanChay();
        tonKhoTab = new ThongKeTonKho();
        tongQuanTab = new ThongKeTongQuan();
        trongThangTab = new ThongKeTrongThang();
        khoangThoiGianTab = new ThongKeTuNgayDenNgay();
    }

    private void addTabs() {
        tabPaneThongKe.add("Doanh thu", doanhThuTab);
        tabPaneThongKe.add("Doanh thu từng năm", doanhThuTungNamTab);
        tabPaneThongKe.add("Doanh thu từng tháng", doanhThuTungThangTab);
        tabPaneThongKe.add("Khách hàng", khachHangTab);
        tabPaneThongKe.add("Nhà cung cấp", nhaCungCapTab);
        tabPaneThongKe.add("Sản phẩm bán chạy", sanPhamBanChayTab);
        tabPaneThongKe.add("Tồn kho", tonKhoTab);
        tabPaneThongKe.add("Tổng quan", tongQuanTab);
        tabPaneThongKe.add("Trong tháng", trongThangTab);
        tabPaneThongKe.add("Khoảng thời gian", khoangThoiGianTab);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPaneThongKe;
    // End of variables declaration//GEN-END:variables

}
