/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package GUI.TTinh;

import BUS.NotHuongBUS;
import DTO.NotHuongDTO;
import DTO.ThuongHieuDTO;
import com.formdev.flatlaf.extras.FlatSVGIcon;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author QUAN
 */
public class NotHuong extends javax.swing.JPanel {

    /** Creates new form NotHuong */
    public NotHuong() {
        initComponents();
        setUpTable();
        addIcon();
        loadDataToTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollThuongHieu = new javax.swing.JScrollPane();
        tblNotHuong = new javax.swing.JTable();
        pnlTop = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        lblThuongHieu = new javax.swing.JLabel();
        tenThuongHieu = new javax.swing.JPanel();
        lblTenThuongHieu = new javax.swing.JLabel();
        txtTenThuongHieu = new javax.swing.JTextField();
        pnlLeft = new javax.swing.JPanel();
        btnThemNotHuong = new javax.swing.JButton();
        btnSuaNotHuong = new javax.swing.JButton();
        btnXoaNotHuong = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tblNotHuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cam Bergamot "},
                {"2", "Hoa Nhài"},
                {"3", "Hoa Hồng"},
                {"4", "Tobacco "}
            },
            new String [] {
                "Mã nốt hương", "Tên nốt hương"
            }
        ));
        scrollThuongHieu.setViewportView(tblNotHuong);
        if (tblNotHuong.getColumnModel().getColumnCount() > 0) {
            tblNotHuong.getColumnModel().getColumn(1).setResizable(false);
        }

        add(scrollThuongHieu, java.awt.BorderLayout.CENTER);

        title.setBackground(new java.awt.Color(255, 51, 0));
        title.setForeground(new java.awt.Color(255, 255, 255));

        lblThuongHieu.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblThuongHieu.setForeground(new java.awt.Color(255, 255, 255));
        lblThuongHieu.setText("NỐT HƯƠNG NƯỚC HOA");
        title.add(lblThuongHieu);

        tenThuongHieu.setBackground(new java.awt.Color(255, 255, 255));

        lblTenThuongHieu.setText("Tên nốt hương:");
        tenThuongHieu.add(lblTenThuongHieu);

        txtTenThuongHieu.setMinimumSize(new java.awt.Dimension(150, 30));
        txtTenThuongHieu.setPreferredSize(new java.awt.Dimension(150, 30));
        tenThuongHieu.add(txtTenThuongHieu);

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tenThuongHieu, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tenThuongHieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setPreferredSize(new java.awt.Dimension(130, 580));

        btnThemNotHuong.setText("Thêm");
        btnThemNotHuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNotHuongActionPerformed(evt);
            }
        });

        btnSuaNotHuong.setText("Sửa");
        btnSuaNotHuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNotHuongActionPerformed(evt);
            }
        });

        btnXoaNotHuong.setText("Xóa");
        btnXoaNotHuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNotHuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThemNotHuong, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(btnSuaNotHuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnXoaNotHuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnThemNotHuong, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaNotHuong, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaNotHuong, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        add(pnlLeft, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNotHuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNotHuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemNotHuongActionPerformed

    private void btnSuaNotHuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNotHuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaNotHuongActionPerformed

    private void btnXoaNotHuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNotHuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaNotHuongActionPerformed

    private void setUpTable() {
        // Set ẩn hiển thị ô vuông khi bấm vào cell 
        tblNotHuong.setFocusable(false);
        
        // Set không cho cell có thể chỉnh sửa 
        tblNotHuong.setDefaultEditor(Object.class, null);
    }
    
    private void addIcon() {
        btnThemNotHuong.setIcon(new FlatSVGIcon("./res/icon/add.svg"));
        btnSuaNotHuong.setIcon(new FlatSVGIcon("./res/icon/edit.svg"));
        btnXoaNotHuong.setIcon(new FlatSVGIcon("./res/icon/delete.svg"));
    }

    private void loadDataToTable() {
        NotHuongBUS notHuongBUS = new NotHuongBUS();
        ArrayList<NotHuongDTO> notHuongDTOArrayList = notHuongBUS.getAllNotHuongs();

        DefaultTableModel model = (DefaultTableModel) tblNotHuong.getModel();
        model.setRowCount(0);

        for (NotHuongDTO notHuongDTO : notHuongDTOArrayList) {
            model.addRow(new Object[]{
                    notHuongDTO.getId(),
                    notHuongDTO.getName()
            });
        }

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblNotHuong.getColumnCount(); i++) {
            tblNotHuong.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaNotHuong;
    private javax.swing.JButton btnThemNotHuong;
    private javax.swing.JButton btnXoaNotHuong;
    private javax.swing.JLabel lblTenThuongHieu;
    private javax.swing.JLabel lblThuongHieu;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrollThuongHieu;
    private javax.swing.JTable tblNotHuong;
    private javax.swing.JPanel tenThuongHieu;
    private javax.swing.JPanel title;
    private javax.swing.JTextField txtTenThuongHieu;
    // End of variables declaration//GEN-END:variables

}
