/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package GUI.NQuyen;


import java.sql.Statement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


import util.DBConnection;

/**
 *
 * @author hoang
 */
public class ThemNQuyen extends javax.swing.JPanel {

    /** Creates new form ThemNQuyen */
    public ThemNQuyen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfTenNhomQuyen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cbNCCthem = new javax.swing.JCheckBox();
        cbNCCsua = new javax.swing.JCheckBox();
        cbNCCxoa = new javax.swing.JCheckBox();
        cbNCCchitiet = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cbPNthem = new javax.swing.JCheckBox();
        cbPNsua = new javax.swing.JCheckBox();
        cbPNxoa = new javax.swing.JCheckBox();
        cbPNchitiet = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        cbKHthem = new javax.swing.JCheckBox();
        cbKHsua = new javax.swing.JCheckBox();
        cbKHxoa = new javax.swing.JCheckBox();
        cbKHchitiet = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        lab = new javax.swing.JLabel();
        cbPXthem = new javax.swing.JCheckBox();
        cbPXsua = new javax.swing.JCheckBox();
        cbPXxoa = new javax.swing.JCheckBox();
        cbPXchitiet = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cbSPthem = new javax.swing.JCheckBox();
        cbSPsua = new javax.swing.JCheckBox();
        cbSPxoa = new javax.swing.JCheckBox();
        cbSPchitiet = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        cbTHthem = new javax.swing.JCheckBox();
        cbTHsua = new javax.swing.JCheckBox();
        cbTHxoa = new javax.swing.JCheckBox();
        cbTHchitiet = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        cbLthem = new javax.swing.JCheckBox();
        cbLsua = new javax.swing.JCheckBox();
        cbLxoa = new javax.swing.JCheckBox();
        cbLchitiet = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        cbXXthem = new javax.swing.JCheckBox();
        cbXXsua = new javax.swing.JCheckBox();
        cbXXxoa = new javax.swing.JCheckBox();
        cbXXchitiet = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        lb = new javax.swing.JLabel();
        cbKVKthem = new javax.swing.JCheckBox();
        cbKVKsua = new javax.swing.JCheckBox();
        cbKVKxoa = new javax.swing.JCheckBox();
        cbKVKchitiet = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        cbNVthem = new javax.swing.JCheckBox();
        cbNVsua = new javax.swing.JCheckBox();
        cbNVxoa = new javax.swing.JCheckBox();
        cbNVchitiet = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        cbTKthem = new javax.swing.JCheckBox();
        cbTKsua = new javax.swing.JCheckBox();
        cbTKxoa = new javax.swing.JCheckBox();
        cbTKchitiet = new javax.swing.JCheckBox();
        jPanel15 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        cbPQthem = new javax.swing.JCheckBox();
        cbPQsua = new javax.swing.JCheckBox();
        cbPQxoa = new javax.swing.JCheckBox();
        cbPQchitiet = new javax.swing.JCheckBox();
        jPanel16 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        cbGYthem = new javax.swing.JCheckBox();
        jPanel17 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        cbGNGYsua = new javax.swing.JCheckBox();
        jPanel18 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        cbTKethem = new javax.swing.JCheckBox();
        cbTKesua = new javax.swing.JCheckBox();
        cbTKexoa = new javax.swing.JCheckBox();
        cbTKechitiet = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tfTenNhomQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenNhomQuyenActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên nhóm quyền");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("Quản lý nhà cung cấp");

        cbNCCthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNCCthemActionPerformed(evt);
            }
        });

        cbNCCsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNCCsuaActionPerformed(evt);
            }
        });

        cbNCCxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNCCxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbNCCthem)
                .addGap(136, 136, 136)
                .addComponent(cbNCCsua)
                .addGap(143, 143, 143)
                .addComponent(cbNCCxoa)
                .addGap(155, 155, 155)
                .addComponent(cbNCCchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbNCCchitiet)
                    .addComponent(cbNCCxoa)
                    .addComponent(cbNCCsua)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(cbNCCthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setText("Quản lý phiếu nhập");

        cbPNthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPNthemActionPerformed(evt);
            }
        });

        cbPNsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPNsuaActionPerformed(evt);
            }
        });

        cbPNxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPNxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbPNthem)
                .addGap(136, 136, 136)
                .addComponent(cbPNsua)
                .addGap(143, 143, 143)
                .addComponent(cbPNxoa)
                .addGap(156, 156, 156)
                .addComponent(cbPNchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPNchitiet)
                    .addComponent(cbPNxoa)
                    .addComponent(cbPNsua)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(cbPNthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setText("Quản lý khách hàng");

        cbKHthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKHthemActionPerformed(evt);
            }
        });

        cbKHsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKHsuaActionPerformed(evt);
            }
        });

        cbKHxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKHxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbKHthem)
                .addGap(136, 136, 136)
                .addComponent(cbKHsua)
                .addGap(143, 143, 143)
                .addComponent(cbKHxoa)
                .addGap(157, 157, 157)
                .addComponent(cbKHchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbKHchitiet)
                    .addComponent(cbKHxoa)
                    .addComponent(cbKHsua)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(cbKHthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lab.setText("Quản lý phiếu xuất");

        cbPXthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPXthemActionPerformed(evt);
            }
        });

        cbPXsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPXsuaActionPerformed(evt);
            }
        });

        cbPXxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPXxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbPXthem)
                .addGap(136, 136, 136)
                .addComponent(cbPXsua)
                .addGap(143, 143, 143)
                .addComponent(cbPXxoa)
                .addGap(157, 157, 157)
                .addComponent(cbPXchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPXchitiet)
                    .addComponent(cbPXxoa)
                    .addComponent(cbPXsua)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab)
                        .addComponent(cbPXthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setText("Quản lý sản phẩm");

        cbSPthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSPthemActionPerformed(evt);
            }
        });

        cbSPsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSPsuaActionPerformed(evt);
            }
        });

        cbSPxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSPxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbSPthem)
                .addGap(136, 136, 136)
                .addComponent(cbSPsua)
                .addGap(143, 143, 143)
                .addComponent(cbSPxoa)
                .addGap(157, 157, 157)
                .addComponent(cbSPchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSPchitiet)
                    .addComponent(cbSPxoa)
                    .addComponent(cbSPsua)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(cbSPthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setText("Quản lý thương hiệu");

        cbTHthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTHthemActionPerformed(evt);
            }
        });

        cbTHsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTHsuaActionPerformed(evt);
            }
        });

        cbTHxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTHxoaActionPerformed(evt);
            }
        });

        cbTHchitiet.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbTHthem)
                .addGap(136, 136, 136)
                .addComponent(cbTHsua)
                .addGap(143, 143, 143)
                .addComponent(cbTHxoa)
                .addGap(158, 158, 158)
                .addComponent(cbTHchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTHchitiet)
                    .addComponent(cbTHxoa)
                    .addComponent(cbTHsua)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(cbTHthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setText("Quản lý loại");

        cbLthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLthemActionPerformed(evt);
            }
        });

        cbLsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLsuaActionPerformed(evt);
            }
        });

        cbLxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLxoaActionPerformed(evt);
            }
        });

        cbLchitiet.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbLthem)
                .addGap(136, 136, 136)
                .addComponent(cbLsua)
                .addGap(143, 143, 143)
                .addComponent(cbLxoa)
                .addGap(158, 158, 158)
                .addComponent(cbLchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbLchitiet)
                    .addComponent(cbLxoa)
                    .addComponent(cbLsua)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(cbLthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setText("Quản lý xuất xứ");

        cbXXthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbXXthemActionPerformed(evt);
            }
        });

        cbXXsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbXXsuaActionPerformed(evt);
            }
        });

        cbXXxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbXXxoaActionPerformed(evt);
            }
        });

        cbXXchitiet.setEnabled(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbXXthem)
                .addGap(136, 136, 136)
                .addComponent(cbXXsua)
                .addGap(143, 143, 143)
                .addComponent(cbXXxoa)
                .addGap(159, 159, 159)
                .addComponent(cbXXchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbXXchitiet)
                    .addComponent(cbXXxoa)
                    .addComponent(cbXXsua)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(cbXXthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        lb.setText("Quản lý khu vực kho");

        cbKVKthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKVKthemActionPerformed(evt);
            }
        });

        cbKVKsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKVKsuaActionPerformed(evt);
            }
        });

        cbKVKxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKVKxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbKVKthem)
                .addGap(136, 136, 136)
                .addComponent(cbKVKsua)
                .addGap(143, 143, 143)
                .addComponent(cbKVKxoa)
                .addGap(161, 161, 161)
                .addComponent(cbKVKchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbKVKchitiet)
                    .addComponent(cbKVKxoa)
                    .addComponent(cbKVKsua)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb)
                        .addComponent(cbKVKthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setText("Quản lý nhân viên");

        cbNVthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNVthemActionPerformed(evt);
            }
        });

        cbNVsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNVsuaActionPerformed(evt);
            }
        });

        cbNVxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNVxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbNVthem)
                .addGap(136, 136, 136)
                .addComponent(cbNVsua)
                .addGap(143, 143, 143)
                .addComponent(cbNVxoa)
                .addGap(161, 161, 161)
                .addComponent(cbNVchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbNVchitiet)
                    .addComponent(cbNVxoa)
                    .addComponent(cbNVsua)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(cbNVthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel32.setText("Quản lý tài khoản");

        cbTKthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTKthemActionPerformed(evt);
            }
        });

        cbTKsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTKsuaActionPerformed(evt);
            }
        });

        cbTKxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTKxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbTKthem)
                .addGap(136, 136, 136)
                .addComponent(cbTKsua)
                .addGap(143, 143, 143)
                .addComponent(cbTKxoa)
                .addGap(161, 161, 161)
                .addComponent(cbTKchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTKchitiet)
                    .addComponent(cbTKxoa)
                    .addComponent(cbTKsua)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(cbTKthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel33.setText("Quản lý phân quyền");

        cbPQthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPQthemActionPerformed(evt);
            }
        });

        cbPQsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPQsuaActionPerformed(evt);
            }
        });

        cbPQxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPQxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cbPQthem)
                .addGap(136, 136, 136)
                .addComponent(cbPQsua)
                .addGap(143, 143, 143)
                .addComponent(cbPQxoa)
                .addGap(162, 162, 162)
                .addComponent(cbPQchitiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPQchitiet)
                    .addComponent(cbPQxoa)
                    .addComponent(cbPQsua)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(cbPQthem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel34.setText("Góp ý");

        cbGYthem.setText("Thêm góp ý");
        cbGYthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGYthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(cbGYthem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(cbGYthem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel35.setText("Quản lý góp ý");

        cbGNGYsua.setText("Xem và sửa góp ý");
        cbGNGYsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGNGYsuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(cbGNGYsua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbGNGYsua)
                    .addComponent(jLabel35))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jLabel36.setText("Thống kê");

        cbTKethem.setText("Tổng quan");
        cbTKethem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTKethemActionPerformed(evt);
            }
        });

        cbTKesua.setText("Doanh thu");
        cbTKesua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTKesuaActionPerformed(evt);
            }
        });

        cbTKexoa.setText("Kho, khách hàng, nhà cung cấp");
        cbTKexoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTKexoaActionPerformed(evt);
            }
        });

        cbTKechitiet.setText("Sản phẩm bán chạy");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(cbTKethem)
                .addGap(35, 35, 35)
                .addComponent(cbTKesua)
                .addGap(32, 32, 32)
                .addComponent(cbTKexoa)
                .addGap(38, 38, 38)
                .addComponent(cbTKechitiet)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cbTKethem)
                    .addComponent(cbTKesua)
                    .addComponent(cbTKexoa)
                    .addComponent(cbTKechitiet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Thêm");

        jLabel3.setText("Sửa");

        jLabel4.setText("Xóa");

        jLabel5.setText("Chi tiết");

        btnLuu.setBackground(new java.awt.Color(0, 102, 204));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu thông tin");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(204, 0, 102));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTenNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTenNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfTenNhomQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenNhomQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenNhomQuyenActionPerformed

    private void cbNCCthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNCCthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNCCthemActionPerformed

    private void cbNCCsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNCCsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNCCsuaActionPerformed

    private void cbNCCxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNCCxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNCCxoaActionPerformed

    private void cbPNthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPNthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPNthemActionPerformed

    private void cbPNsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPNsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPNsuaActionPerformed

    private void cbPNxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPNxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPNxoaActionPerformed

    private void cbKHthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKHthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKHthemActionPerformed

    private void cbKHsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKHsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKHsuaActionPerformed

    private void cbKHxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKHxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKHxoaActionPerformed

    private void cbPXthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPXthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPXthemActionPerformed

    private void cbPXsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPXsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPXsuaActionPerformed

    private void cbPXxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPXxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPXxoaActionPerformed

    private void cbSPthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSPthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSPthemActionPerformed

    private void cbSPsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSPsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSPsuaActionPerformed

    private void cbSPxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSPxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSPxoaActionPerformed

    private void cbTHthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTHthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTHthemActionPerformed

    private void cbTHsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTHsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTHsuaActionPerformed

    private void cbTHxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTHxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTHxoaActionPerformed

    private void cbLthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLthemActionPerformed

    private void cbLsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLsuaActionPerformed

    private void cbLxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLxoaActionPerformed

    private void cbXXthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbXXthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbXXthemActionPerformed

    private void cbXXsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbXXsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbXXsuaActionPerformed

    private void cbXXxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbXXxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbXXxoaActionPerformed

    private void cbKVKthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKVKthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKVKthemActionPerformed

    private void cbKVKsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKVKsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKVKsuaActionPerformed

    private void cbKVKxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKVKxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKVKxoaActionPerformed

    private void cbNVthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNVthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNVthemActionPerformed

    private void cbNVsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNVsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNVsuaActionPerformed

    private void cbNVxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNVxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNVxoaActionPerformed

    private void cbTKthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTKthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTKthemActionPerformed

    private void cbTKsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTKsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTKsuaActionPerformed

    private void cbTKxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTKxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTKxoaActionPerformed

    private void cbPQthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPQthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPQthemActionPerformed

    private void cbPQsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPQsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPQsuaActionPerformed

    private void cbPQxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPQxoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPQxoaActionPerformed

    private void cbGYthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGYthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGYthemActionPerformed

    private void cbGNGYsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGNGYsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGNGYsuaActionPerformed

    private void cbTKethemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTKethemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTKethemActionPerformed

    private void cbTKesuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTKesuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTKesuaActionPerformed

    private void cbTKexoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTKexoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTKexoaActionPerformed
    

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {
    String tenNhom = tfTenNhomQuyen.getText().trim();
    if (tenNhom.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhóm quyền!");
        return;
    }

    // 1. Tạo nhóm quyền mới và lấy về generated groupId
    int groupId = -1;
    try (java.sql.Connection conn = DBConnection.getConnection()) {
        String insertGroup = "INSERT INTO rolegroup(name) VALUES (?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(insertGroup, java.sql.Statement.RETURN_GENERATED_KEYS);
        pst.setString(1, tenNhom);
        pst.executeUpdate();
        java.sql.ResultSet rs = pst.getGeneratedKeys();
        if (rs.next()) {
            groupId = rs.getInt(1);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi tạo nhóm quyền!");
        return;
    }

    // 2. Chuẩn bị map từ mỗi JCheckBox → moduleId
    Map<JCheckBox,Integer> checkboxes = new LinkedHashMap<>();
    checkboxes.put(cbSPthem,      1);
    checkboxes.put(cbSPsua,       1);
    checkboxes.put(cbSPxoa,       1);
    checkboxes.put(cbSPchitiet,   1);
    checkboxes.put(cbKHthem,      3);
    checkboxes.put(cbKHsua,       3);
    checkboxes.put(cbKHxoa,       3);
    checkboxes.put(cbKHchitiet,   3);
    checkboxes.put(cbNVthem,      4);
    checkboxes.put(cbNVsua,       4);
    checkboxes.put(cbNVxoa,       4);
    checkboxes.put(cbNVchitiet,   4);
    checkboxes.put(cbPNthem,      5);
    checkboxes.put(cbPNsua,       5);
    checkboxes.put(cbPNxoa,       5);
    checkboxes.put(cbPNchitiet,   5);
    checkboxes.put(cbTHthem,      6);
    checkboxes.put(cbTHsua,       6);
    checkboxes.put(cbTHxoa,       6);
    checkboxes.put(cbTHchitiet,   6);
    checkboxes.put(cbNCCthem,     7);
    checkboxes.put(cbNCCsua,      7);
    checkboxes.put(cbNCCxoa,      7);
    checkboxes.put(cbNCCchitiet,  7);
    checkboxes.put(cbTKthem,      8);
    checkboxes.put(cbTKsua,       8);
    checkboxes.put(cbTKxoa,       8);
    checkboxes.put(cbTKchitiet,   8);
    checkboxes.put(cbPQthem,      9);
    checkboxes.put(cbPQsua,       9);
    checkboxes.put(cbPQxoa,       9);
    checkboxes.put(cbPQchitiet,   9);
    checkboxes.put(cbGYthem,     10);
    checkboxes.put(cbGNGYsua,    10);
    checkboxes.put(cbTKethem,    11);
    checkboxes.put(cbTKesua,     11);
    checkboxes.put(cbTKexoa,     11);
    checkboxes.put(cbTKechitiet, 11);

    // 3. Tập hợp các moduleId cần lưu (nếu ít nhất 1 trong 4 isSelected)
    Set<Integer> selectedRoleIds = new HashSet<>();
    for (var e : checkboxes.entrySet()) {
        if (e.getKey().isSelected()) {
            selectedRoleIds.add(e.getValue());
        }
    }

    // 4. Lưu vào role_rolegroup
    try (java.sql.Connection conn = DBConnection.getConnection()) {
        String insertRR = "INSERT INTO role_rolegroup(role_id, rolegroup_id, status) VALUES (?, ?, 1)";
        java.sql.PreparedStatement pst = conn.prepareStatement(insertRR);

        for (Integer roleId : selectedRoleIds) {
            pst.setInt(1, roleId);
            pst.setInt(2, groupId);
            pst.addBatch();
        }
        pst.executeBatch();

        JOptionPane.showMessageDialog(this, "Thêm nhóm quyền thành công!");
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi thêm quyền cho nhóm!");
    }
}

                                      

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JCheckBox cbGNGYsua;
    private javax.swing.JCheckBox cbGYthem;
    private javax.swing.JCheckBox cbKHchitiet;
    private javax.swing.JCheckBox cbKHsua;
    private javax.swing.JCheckBox cbKHthem;
    private javax.swing.JCheckBox cbKHxoa;
    private javax.swing.JCheckBox cbKVKchitiet;
    private javax.swing.JCheckBox cbKVKsua;
    private javax.swing.JCheckBox cbKVKthem;
    private javax.swing.JCheckBox cbKVKxoa;
    private javax.swing.JCheckBox cbLchitiet;
    private javax.swing.JCheckBox cbLsua;
    private javax.swing.JCheckBox cbLthem;
    private javax.swing.JCheckBox cbLxoa;
    private javax.swing.JCheckBox cbNCCchitiet;
    private javax.swing.JCheckBox cbNCCsua;
    private javax.swing.JCheckBox cbNCCthem;
    private javax.swing.JCheckBox cbNCCxoa;
    private javax.swing.JCheckBox cbNVchitiet;
    private javax.swing.JCheckBox cbNVsua;
    private javax.swing.JCheckBox cbNVthem;
    private javax.swing.JCheckBox cbNVxoa;
    private javax.swing.JCheckBox cbPNchitiet;
    private javax.swing.JCheckBox cbPNsua;
    private javax.swing.JCheckBox cbPNthem;
    private javax.swing.JCheckBox cbPNxoa;
    private javax.swing.JCheckBox cbPQchitiet;
    private javax.swing.JCheckBox cbPQsua;
    private javax.swing.JCheckBox cbPQthem;
    private javax.swing.JCheckBox cbPQxoa;
    private javax.swing.JCheckBox cbPXchitiet;
    private javax.swing.JCheckBox cbPXsua;
    private javax.swing.JCheckBox cbPXthem;
    private javax.swing.JCheckBox cbPXxoa;
    private javax.swing.JCheckBox cbSPchitiet;
    private javax.swing.JCheckBox cbSPsua;
    private javax.swing.JCheckBox cbSPthem;
    private javax.swing.JCheckBox cbSPxoa;
    private javax.swing.JCheckBox cbTHchitiet;
    private javax.swing.JCheckBox cbTHsua;
    private javax.swing.JCheckBox cbTHthem;
    private javax.swing.JCheckBox cbTHxoa;
    private javax.swing.JCheckBox cbTKchitiet;
    private javax.swing.JCheckBox cbTKechitiet;
    private javax.swing.JCheckBox cbTKesua;
    private javax.swing.JCheckBox cbTKethem;
    private javax.swing.JCheckBox cbTKexoa;
    private javax.swing.JCheckBox cbTKsua;
    private javax.swing.JCheckBox cbTKthem;
    private javax.swing.JCheckBox cbTKxoa;
    private javax.swing.JCheckBox cbXXchitiet;
    private javax.swing.JCheckBox cbXXsua;
    private javax.swing.JCheckBox cbXXthem;
    private javax.swing.JCheckBox cbXXxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel lb;
    private javax.swing.JTextField tfTenNhomQuyen;
    // End of variables declaration//GEN-END:variables

}
